from sessionPlanGenerator import generate_session_plan_text

age = input("What age group are you coaching?\n")
cgoals = input("What are your expected outcomes, as a coach from this session?\n")
pgoals = input("What are your expected outcomes, for the players from this session?\n")
date = input("What date is this session on during?\n")
venue = input("Where is this session taking place?\n")
duration = input("How long is this session going on for?\n") 
equipment = input("What equipment do you plan to use?\n")
safety = input("What safety measures have to be considered?\n")
warmup = input("What is the planned warmup routine?\n")
skills = input("What skills do you look to deal with in this session?\n")
drills = input("What drills are you looking to implement in this session?\n")
games = input("What games are you looking to use in this session?\n")
cooldown = input("What is the planned cooldown routine?\n")
eval = input("After this session, what did you gain from it?\n")